Map {
  background-color: transparent;
  }
 #ne_110m_admin_0_countries_lakes {
  polygon-pattern-file: url('img/dot-pattern.png');
  polygon-pattern-alignment: global;
  polygon-pattern-opacity:0.25;
    /* List from https://www.digitalglobe.com/products/digitalglobe-basemap*/
    /* Central America */
    [sovereignt = 'El Salvador'],
    [sovereignt = 'Guatemala'],
    [sovereignt = 'Honduras'],
    [sovereignt = 'Mexico'],
    [sovereignt = 'Nicaragua'],

    /* South America */
    [sovereignt = 'Argentina'],
    [sovereignt = 'Belize'],

    /* ASIA Pacific */
    [geounit = 'Australia'],
    [sovereignt = 'Bahrain'],
    [sovereignt = 'British Indian Ocean Territory'],
    [sovereignt = 'India'],
    [sovereignt = 'Iran'],
    [sovereignt = 'Iraq'],
    [sovereignt = 'Israel'],
    [sovereignt = 'Japan'],
    [sovereignt = 'Jordan'],
    [sovereignt = 'Kazakhstan'],
    [sovereignt = 'Kuwait'],
    [sovereignt = 'Kyrgyzstan'],
    [sovereignt = 'Lebanon'],
    [sovereignt = 'Maldives'],
    [sovereignt = 'Mauritius'],
    [sovereignt = 'North Korea'],
    [sovereignt = 'Oman'],
    [sovereignt = 'Pakistan'],
    [sovereignt = 'Palestinian Territory'],
    [sovereignt = 'Qatar'],
    [sovereignt = 'Saudi Arabia'],
    [sovereignt = 'South Korea'],
    [sovereignt = 'Sri Lanka'],
    [sovereignt = 'Syria'],
    [sovereignt = 'Tajikistan'],
    [sovereignt = 'Turkmenistan'],
    [sovereignt = 'United Arab Emirates'],
    [sovereignt = 'Uzbekistan'],
    [sovereignt = 'Yemen'],

    /* AFRICA */
    [geounit = 'Kenya'], /* Kenya */
    [sovereignt = 'Algeria'],
    [sovereignt = 'Angola'],
    [sovereignt = 'Benin'],
    [sovereignt = 'Botswana'],
    [sovereignt = 'Burkina Faso'],
    [sovereignt = 'Burundi'],
    [sovereignt = 'Cameroon'],
    [sovereignt = 'Central African Republic'],
    [sovereignt = 'Chad'],
    [sovereignt = 'Comoros'],
    [sovereignt = 'Congo'],
    [sovereignt = 'Congo DRC'],
    [sovereignt = 'Côte d’Ivoire'],
    [sovereignt = 'Djibouti'],
    [sovereignt = 'Egypt'],
    [sovereignt = 'Equatorial Guinea'],
    [sovereignt = 'Eritrea'],
    [sovereignt = 'Ethiopia'],
    [sovereignt = 'Gabon'],
    [sovereignt = 'Gambia'],
    [sovereignt = 'Ghana'],
    [sovereignt = 'Guinea'],
    [sovereignt = 'Guinea-Bissau'],
    [sovereignt = 'Kenya'],
    [sovereignt = 'Lesotho'],
    [sovereignt = 'Liberia'],
    [sovereignt = 'Libya'],
    [sovereignt = 'Madagascar'],
    [sovereignt = 'Malawi'],
    [sovereignt = 'Mali'],
    [sovereignt = 'Mauritania'],
    [sovereignt = 'Mayotte'],
    [sovereignt = 'Morocco'],
    [sovereignt = 'Mozambique'],
    [sovereignt = 'Namibia'],
    [sovereignt = 'Niger'],
    [sovereignt = 'Nigeria'],
    [sovereignt = 'Reunion'],
    [sovereignt = 'Rwanda'],
    [sovereignt = 'Sao Tome and Principe'],
    [sovereignt = 'Senegal'],
    [sovereignt = 'Seychelles'],
    [sovereignt = 'Sierra Leone'],
    [sovereignt = 'Somalia'],
    [sovereignt = 'South Africa'],
    [sovereignt = 'South Sudan'],
    [sovereignt = 'Sudan'],
    [sovereignt = 'Swaziland'],
    [sovereignt = 'Tanzania'],
    [sovereignt = 'Togo'],
    [sovereignt = 'Tunisia'],
    [sovereignt = 'Uganda'],
    [sovereignt = 'Zambia'],
    [sovereignt = 'Zimbabwe'] {
      polygon-pattern-opacity: 1;
    }
}
