

importData.coverage = [{
  section: 'BASEMAP +VIVID: COUNTRY-WIDE IMAGERY',
  coverage: [
    'Current Available Countries'
  ]}, {
	  section: 'Central America',
	  coverage: [
		'El Salvador',
		'Guatemala',
		'Honduras',
		'Mexico',
		'Nicaragua'
  ]}, {
    section: 'South America',
    coverage: [
      'Argentina',
      'Belize'
  ]}, {
    section: 'Asia/Pacific',
    coverage: [
      'Australia',
      'Bahrain',
      'British Indian Ocean Territory',
      'India',
      'Iran',
      'Iraq',
      'Israel',
      'Japan',
      'Jordan',
      'Kazakhstan',
      'Kuwait',
      'Kyrgyzstan',
      'Lebanon',
      'Maldives',
      'Mauritius',
      'North Korea',
      'Oman',
      'Pakistan',
      'Palestinian Territory',
      'Qatar',
      'Saudi Arabia',
      'South Korea',
      'Sri Lanka',
      'Syria',
      'Tajikistan',
      'Turkmenistan',
      'United Arab Emirates',
      'Uzbekistan',
      'Yemen'
  ]}, {
    section: 'Africa',
    coverage: [
      'Algeria',
      'Angola',
      'Benin',
      'Botswana',
      'Burkina Faso',
      'Burundi',
      'Cameroon',
      'Central African Republic',
      'Chad',
      'Comoros',
      'Congo',
      'Congo DRC',
      'Côte d’Ivoire',
      'Djibouti',
      'Egypt',
      'Equatorial Guinea',
      'Eritrea',
      'Ethiopia',
      'Gabon',
      'Gambia',
      'Ghana',
      'Guinea',
      'Guinea-Bissau',
      'Kenya',
      'Lesotho',
      'Liberia',
      'Libya',
      'Madagascar',
      'Malawi',
      'Mali',
      'Mauritania',
      'Mayotte',
      'Morocco',
      'Mozambique',
      'Namibia',
      'Niger',
      'Nigeria',
      'Reunion',
      'Rwanda',
      'Sao Tome and Principe',
      'Senegal',
      'Seychelles',
      'Sierra Leone',
      'Somalia',
      'South Africa',
      'South Sudan',
      'Sudan',
      'Swaziland',
      'Tanzania',
      'Togo',
      'Tunisia',
      'Uganda',
      'Zambia',
      'Zimbabwe'
  ]
}];
