/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.digitalglobe.iipfoundations.productservice.app;

import com.digitalglobe.iipfoundations.productservice.statushandler.StatusHandler;
import java.awt.Color;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author jthiel
 */
public class ApplicationGUI extends javax.swing.JFrame {

    private static final Logger logger = LoggerFactory.getLogger(ApplicationGUI.class);
    /**
     * Creates new form ApplicationGUI
     */
    public ApplicationGUI() {
        initComponents();
        statusHandlerjButton.setBackground(Color.RED);
        webServerjButton.setBackground(Color.RED);
        
        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            @Override
            public void run() {
                if (jettyServer.isStarted()) {
                    try {
                        jettyServer.stop();
                    } catch (Exception exception) {
                        exception.printStackTrace(System.out);
                    }
                }
                if (statusHandler.isStarted()) {
                    try {
                        statusHandler.stop();
                    } catch (Exception exception) {
                        exception.printStackTrace(System.out);
                    }
                }
            }
        }, "Stop Servers Hook"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webServerjButton = new javax.swing.JButton();
        statusHandlerjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        webServerjButton.setText("Start");
        webServerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webServerjButtonActionPerformed(evt);
            }
        });

        statusHandlerjButton.setText("Start");
        statusHandlerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusHandlerjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(" Web Server");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText(" Status Handler");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusHandlerjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(webServerjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webServerjButton)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusHandlerjButton)
                    .addComponent(jLabel2))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final JettyServer jettyServer = new JettyServer();
    private void webServerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webServerjButtonActionPerformed
        if (jettyServer.isStarted()) {
            webServerjButton.setBackground(Color.RED);
            webServerjButton.setText("Start");
            try {
                jettyServer.stop();
            } catch (Exception ex) {
                logger.error(ex.getMessage());
            }
        } else {
            webServerjButton.setBackground(Color.GREEN);
            webServerjButton.setText("Stop!");
            try {
                jettyServer.start();
            } catch (Exception ex) {
                logger.error(ex.getMessage());
            }
        }
    }//GEN-LAST:event_webServerjButtonActionPerformed

    private final StatusHandler statusHandler = new StatusHandler();
    private void statusHandlerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusHandlerjButtonActionPerformed
        if (statusHandler.isStarted()) {
            statusHandlerjButton.setBackground(Color.RED);
            statusHandlerjButton.setText("Start");
            try {
                statusHandler.stop();
            } catch (InterruptedException ex) {
                logger.error(ex.getMessage());
            }
        } else {
            statusHandlerjButton.setBackground(Color.GREEN);
            statusHandlerjButton.setText("Stop!");
            statusHandler.start();
        }
    }//GEN-LAST:event_statusHandlerjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(()-> new ApplicationGUI().setVisible(true));
                    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton statusHandlerjButton;
    private javax.swing.JButton webServerjButton;
    // End of variables declaration//GEN-END:variables
}
